project_id = "lbepdlwxcgvzfqydcykm"

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.generate-content]
verify_jwt = false

[functions.admin-login]
verify_jwt = false

[functions.photo-enhance]
verify_jwt = false

[functions.notify-site-published]
verify_jwt = false

[functions.check-domain-rdap]
verify_jwt = false

[functions.generate-og-image]
verify_jwt = false

[functions.admin-get-pages]
verify_jwt = false

[functions.admin-update-status]
verify_jwt = false

[functions.admin-sync-subscriptions]
verify_jwt = false

[functions.stripe-create-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
